---
#
# The "destroy-aws-instance" role uses the "aws_instance_id" Ansible
# variable to determine which AWS instance to delete. The Jenkins job
# should pass this variable into the playbook via the "--extra-vars"
# option to "ansible-playbook". If this ever changes, it's better to
# fail fast here, instead of proceeding into the "destroy-aws-instance"
# role below.
#
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - fail:
        msg: "Ansible variable 'aws_instance_id' is not defined."
      when: aws_instance_id is not defined

#
# We need to ensure we attempt to destroy the AWS instance from the same
# region that it was created in. The "create-build-slave.yml" playbook
# is used to create the instance, so we need to ensure we use the same
# region here, that's used in that playbook.
#
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: "us-west-1"
  roles:
    - destroy-aws-instance
