---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Add new DCenter instance to inventory
      add_host:
        hostname: "{{ instance_dns }}"
        ansible_ssh_user: "{{ omnios_ssh_user }}"
        ansible_ssh_pass: "{{ omnios_ssh_pass }}"
  roles:
    - omnios-credentials

- hosts: "{{ instance_dns }}"
  vars:
    jenkins_master: "http://psurya-jenkins.dcenter.delphix.com:8080"
    jenkins_label: "openzfs-build-slave"
  roles:
    - reboot-dc-instance
    - initialize-omnios
    - openzfs-jenkins-slave
